@base = https://vidly-api-production-5b18.up.railway.app/api/customers
@id = 6a30a176fe6f2a398b7d764b

GET {{base}}
Accept: application/json

###

GET {{base}}/{{id}}
Accept: application/json

###
POST {{base}}
Content-Type: application/json

{
    "name":"abdulrahman",
    "phone":"01063030401",
    "isGold":false
}


###
PUT  {{base}}/{{id}}
Content-Type: application/json

{
    "name":"abdularhman sallam",
    "phone":"01063030401",
    "isGold":false
}

###
Delete  {{base}}/{{id}}
