@base = http://localhost:3000/api/genres
@id = 6a30a25f2464ba4c957b9eb9

GET {{base}}
Accept: application/json


###

GET {{base}}/{{id}}
Accept: application/json

###
POST {{base}}
Content-Type: application/json

{
    "name":"action"
}


###
PUT  {{base}}/{{id}}
Content-Type: application/json

{
    "name":"hello"
}

###
Delete  {{base}}/{{id}}
